### ISSUE TITLE
starry crashes when trying to find basic for EBs, following the docs tutorials

### ISSUE THREAD

**Issue by christinahedges** [rodluger/starry#227] opened 2020-01-27 21:08 UTC
Hey Rodrigo,

I am trying to use starry to fit some eclipsing binaries to find basic R1/R2 and F1/F2 parameters. I'm having some trouble when I try to find the map amplitudes using either the starry solve or the exoplanet optimize with pymc3. Starry seems to crash whenever I want to find the map amplitudes. I'm including a MWE example to show what's going on, I don't know if this might be because of something I don't understand in the new update or whether I am just not following the tutorials correctly.

The MWE is at a gist [here](https://gist.github.com/christinahedges/bfa6c064a540e5546dc31ad43fe21e6c)

Thanks!
C

**Comment by rodluger** [comment] 2020-01-27 21:48
I think the issue is that your [prior variance for the spherical harmonic coefficients is zero](https://gist.github.com/christinahedges/bfa6c064a540e5546dc31ad43fe21e6c?short_path=cf1a57d#file-starry-mwe-ipynb-L166), so you get infs when trying to invert the covariance matrix. If you change that to a nonzero value, the code should work.

**Comment by christinahedges** [comment] 2020-01-27 21:58
Hey Rodrigo,

That totally is the issue thanks for helping me out. I am confused, why are there 4 components in the map if I set `ydeg=1` and `udeg=0`?

C

**Comment by rodluger** [comment] 2020-01-27 22:17
When `ydeg=1` you're telling `starry` to use an `l=1` expansion, so the vector has four components: `amp * Y_{0,0}`, `amp * Y_{1,-1}`, `amp * Y_{1,0}` and `amp * Y_{1,1}`. You could try `ydeg=0` if all you want to vary is the amplitude -- but I'm not sure I've tested that case!

**Comment by christinahedges** [comment] 2020-01-27 22:29
Hi,

Got it, the functionality to set `ydeg=0` would be really useful. I'm finding that I can set it and create and optimize a starry model with `ydeg=0`, but when I use `sys.solve` to find the map parameters I get a ValueError for an invalid `l`.

**Comment by rodluger** [comment] 2020-01-27 22:34
OK, let's keep this issue open and I'll work on allowing users to solve for just the amplitude.

**Comment by rodluger** [comment] 2020-01-27 22:35
As a workaround, you can set `L` for all components after the first to a very small value and `mu` for those components to zero.

**Comment by christinahedges** [comment] 2020-01-27 22:36
Thanks, for now I am only using the first component and disregarding the rest, and I'll set the L's to be very small. Thanks!

C

**Comment by rodluger** [comment] 2021-02-22 21:32
This is a duplicate of #253. Will be closed by #270.

**Closed** 2021-02-24 14:18 UTC
Labels: bug
