### ISSUE TITLE
Null velocity vector for secondary

### ISSUE THREAD

**Issue by trevordavid** [rodluger/starry#229] opened 2020-02-20 20:30 UTC
When computing the RVs for a system, the secondary RV array is returned as zeros
`model_rv = sys.rv(t_rv, total=False)`

This would be useful for SB2s (and RM effect during secondary eclipse) and computing planetary orbital velocities (for e.g. CCF searches of atmospheric signatures).

**Comment by rodluger** [comment] 2021-02-23 22:05
@trevordavid It took me one year and three days, but I finally fixed this! I originally thought that what you were seeing was intended behavior, but turns out it was a bug, which is now fixed on the `restructure` branch and will be merged into master shortly (#270). This is the expected behavior when `total=False`:

```python
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
import starry

# Instantiate a simple system
starry.config.lazy = False
A = starry.Primary(starry.Map(rv=True), m=1.0, mass_unit=u.Msun)
b = starry.Secondary(
    starry.Map(rv=True),
    porb=0.615198,
    m=0.815,
    mass_unit=u.earthMass,
    time_unit=u.year,
)
c = starry.Secondary(
    starry.Map(rv=True),
    porb=1.0,
    m=1,
    mass_unit=u.earthMass,
    time_unit=u.year,
)
sys = starry.System(A, b, c, time_unit=u.year)

# Compute the RV over 2 years
t = np.linspace(0, 2, 1000)
rv = sys.rv(t, total=False, keplerian=True)

# Plot the stellar RV contributions in m/s
plt.plot(t, rv[0], label="sun")
plt.plot(t, rv[1], label="venus")
plt.plot(t, rv[2], label="earth")
plt.xlabel("time [yrs]")
plt.legend()
plt.ylabel("stellar rv contribution [m/s]");
```

![image](https://user-images.githubusercontent.com/9323819/108914152-f2c0e880-75f8-11eb-98c5-fd3ead1eccde.png)


Each row in the returned `rv` matrix is the contribution to the *stellar* RV due to each of the bodies in the system (in this case, the Sun, Venus, and the Earth, in that order).
The blue line shows the Sun's contribution to its own RV, and it's zero. That's because there are no spots on its surface inducing an RV anomaly and I'm not modeling the Rossiter-McLaughlin effect. The orange and green lines are the Keplerian contribution to the Sun's RV from Venus and the Earth, respectively. If those planets had surface features of their own rotating in and out of view, the anomaly due to those would show up in these curves as well.

The sum of these three curves is what you would get if `total=True`, which is almost always what you want to do.

The specific thing you requested -- the ability to compute the *planet's* own radial velocity -- is not explicitly implemented, but it's easy to do from conservation of momentum:

```python
# Compute the mass ratios, minding the units!
msun_mvenus = ((A.m * A.mass_unit) / (b.m * b.mass_unit)).decompose()
msun_mearth = ((A.m * A.mass_unit) / (c.m * c.mass_unit)).decompose()

# Conservation of momentum
rv_venus = -rv[1] * msun_mvenus
rv_earth = -rv[2] * msun_mearth

# Plot the individual planet RVs in km/s
plt.plot(t, 1e-3 * rv_venus, label="venus")
plt.plot(t, 1e-3 * rv_earth, label="earth")
plt.xlabel("time [yrs]")
plt.legend()
plt.ylabel("planetary rv [km/s]");
```

![image](https://user-images.githubusercontent.com/9323819/108914203-04a28b80-75f9-11eb-81ce-e3e76e894634.png)

I've included all this info in the docstring for the method. Thanks for helping me catch these issues, and let me know if you have any other questions/suggestions!

**Closed** 2021-02-24 14:18 UTC
Labels: enhancement
